version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: llm-backend
    env_file: .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - DB_URL=${DB_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  ui:
    build:
      context: .
      dockerfile: Dockerfile.UI
    container_name: llm-ui
    env_file: .env
    environment:
      - API=${API:-http://backend:8000}
    ports:
      - "7860:7860"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

